# Configuration du serveur
server.port=8080

# Configuration de la base de données (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/fixyhome?stringtype=unspecified&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration UTF-8 pour PostgreSQL
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=UTF-8;characterSetResults=UTF-8

# Configuration H2 Console (désactivée pour PostgreSQL)
# spring.h2.console.enabled=false
# spring.h2.console.path=/h2-console

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
# spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.query.substitutions=true=1, false=0

# Configuration JWT
jwt.secret=PqRGm5Kp1gw031LbUAuFc9CeDIMyHbOyuwOKNIgp9s0wOLxNiLEHyEisk+JReYNfFv9xCcb01BJE4TxxBPqVHw==
jwt.expiration=86400000

# Configuration CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=false

# Logging
logging.level.com.fixyhome=DEBUG
logging.level.org.springframework.security=DEBUG
